name: Update README

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          sed -i 's/Last updated: .*/Last updated: '"$(date +'%Y-%m-%d')"'/' README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest date"
          git push
